import type { NextPage } from "next";
import Head from "next/head";
import { TODOType } from "../@types";
import Todo from "../components/Todo";

import { useState } from "react";

const Home: NextPage = () => {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col justify-center items-center p-4 bg-gray-50">
        <div className="bg-gray-50 w-full max-w-lg h-screen flex flex-col items-center">
          <header className="h-16 w-full bg-blue-500 text-white flex items-center justify-center">
            <h1 className="text-lg">Task Management {" > "}Home</h1>
          </header>
          <div className="w-5/6 mt-10 flex flex-col items-start">
            <h2 className="text-2xl">Add a new Task</h2>
            <input
              type="text"
              className="w-full mt-5 p-4 border-b border-b-slate-600 bg-slate-200"
              placeholder="Title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}></input>
            <textarea
              className="w-full h-32 mt-5 p-4 border-b border-b-slate-600 bg-slate-200"
              placeholder="Description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}></textarea>
            <button className="w-full h-12 rounded-md shadow-md bg-blue-700 text-white font-bold mt-5 transition-all duration-300 ease-out hover:bg-blue-800">
              + ADD
            </button>
          </div>
          <main className="mt-10 bg-blue-600 text-white w-full h-full rounded-t-3xl flex flex-col items-center overflow-hidden">
            <h1 className="ml-10 mt-5 text-xl w-full">Tasks</h1>
            <div className="w-11/12 bg-blue-300 h-full mt-2 p-4 rounded-t-3xl grid grid-cols-2 overflow-y-scroll"></div>
          </main>
        </div>
      </div>
    </>
  );
};

export default Home;
